# Generated by Django 2.1.4 on 2019-12-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='boys_dress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('price', models.IntegerField(default=0)),
                ('image1', models.ImageField(blank=True, upload_to='media')),
                ('image2', models.ImageField(blank=True, upload_to='media')),
                ('image3', models.ImageField(blank=True, upload_to='media')),
                ('image4', models.ImageField(blank=True, upload_to='media')),
                ('image5', models.ImageField(blank=True, upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='check_out',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('address', models.TextField()),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('price', models.IntegerField(default=0)),
                ('image1', models.ImageField(blank=True, upload_to='media')),
                ('full_name', models.CharField(max_length=500)),
                ('mobile', models.BigIntegerField(default=0)),
                ('landmark', models.CharField(max_length=500)),
                ('address_type', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='girls_dress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('price', models.IntegerField(default=0)),
                ('image1', models.ImageField(blank=True, upload_to='media')),
                ('image2', models.ImageField(blank=True, upload_to='media')),
                ('image3', models.ImageField(blank=True, upload_to='media')),
                ('image4', models.ImageField(blank=True, upload_to='media')),
                ('image5', models.ImageField(blank=True, upload_to='media')),
                ('image6', models.ImageField(blank=True, upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='men_dress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('price', models.IntegerField(default=0)),
                ('image1', models.ImageField(blank=True, upload_to='media')),
                ('image2', models.ImageField(blank=True, upload_to='media')),
                ('image3', models.ImageField(blank=True, upload_to='media')),
                ('image4', models.ImageField(blank=True, upload_to='media')),
                ('image5', models.ImageField(blank=True, upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=500)),
                ('full_name', models.CharField(max_length=500)),
                ('mobile', models.BigIntegerField(default=0)),
                ('landmark', models.CharField(max_length=500)),
                ('address', models.TextField()),
                ('address_type', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='women_dress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('price', models.IntegerField(default=0)),
                ('image1', models.ImageField(blank=True, upload_to='media')),
                ('image2', models.ImageField(blank=True, upload_to='media')),
                ('image3', models.ImageField(blank=True, upload_to='media')),
                ('image4', models.ImageField(blank=True, upload_to='media')),
                ('image5', models.ImageField(blank=True, upload_to='media')),
            ],
        ),
    ]
